spring:
  profiles:
    active: dev
  application:
    name: spring-with-dynamodb
aws:
  dynamo:
    endpoint: ${ENV_DYNAMO_DB_HOST:http://localhost:4566}
  accesskey: ${ENV_AWS_ACCESS_KEY:123}
  secretkey: ${ENV_AWS_SECRET_KEY:123}
